apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  selector:
    app: php-apache
  externalIPs:
  - 10.0.0.4
  - 10.0.0.5
  ports:
    - protocol: TCP
      port: 88
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  labels:
    app: php-apache
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - image: localhost:32000/chat
        name: php-apache

